// Exercise Library — global exercises seeded into Firestore
export const EXERCISE_LIBRARY = [
  { name: "Bench Press", muscle: "Chest", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Squat", muscle: "Legs", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Deadlift", muscle: "Back", equipment: "Barbell", difficulty: "Advanced", isCustom: false },
  { name: "Overhead Press", muscle: "Shoulders", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Pull-up", muscle: "Back", equipment: "Bodyweight", difficulty: "Intermediate", isCustom: false },
  { name: "Dumbbell Row", muscle: "Back", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Bicep Curl", muscle: "Arms", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Lateral Raise", muscle: "Shoulders", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Leg Press", muscle: "Legs", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Romanian Deadlift", muscle: "Legs", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Incline Dumbbell Press", muscle: "Chest", equipment: "Dumbbell", difficulty: "Intermediate", isCustom: false },
  { name: "Cable Fly", muscle: "Chest", equipment: "Cable", difficulty: "Beginner", isCustom: false },
  { name: "Tricep Pushdown", muscle: "Arms", equipment: "Cable", difficulty: "Beginner", isCustom: false },
  { name: "Leg Curl", muscle: "Legs", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Plank", muscle: "Core", equipment: "Bodyweight", difficulty: "Beginner", isCustom: false },
  { name: "Crunches", muscle: "Core", equipment: "Bodyweight", difficulty: "Beginner", isCustom: false },
  { name: "Treadmill", muscle: "Cardio", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Cycling", muscle: "Cardio", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Rowing Machine", muscle: "Cardio", equipment: "Machine", difficulty: "Intermediate", isCustom: false },
  { name: "Incline Barbell Press", muscle: "Chest", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Decline Barbell Press", muscle: "Chest", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Dumbbell Fly", muscle: "Chest", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Chest Press Machine", muscle: "Chest", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Push-up", muscle: "Chest", equipment: "Bodyweight", difficulty: "Beginner", isCustom: false },
  { name: "Lat Pulldown", muscle: "Back", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "T-Bar Row", muscle: "Back", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Seated Cable Row", muscle: "Back", equipment: "Cable", difficulty: "Beginner", isCustom: false },
  { name: "Face Pull", muscle: "Back", equipment: "Cable", difficulty: "Beginner", isCustom: false },
  { name: "Hyperextension", muscle: "Back", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Front Squat", muscle: "Legs", equipment: "Barbell", difficulty: "Advanced", isCustom: false },
  { name: "Hack Squat", muscle: "Legs", equipment: "Machine", difficulty: "Intermediate", isCustom: false },
  { name: "Leg Extension", muscle: "Legs", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Lying Leg Curl", muscle: "Legs", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Calf Raise", muscle: "Legs", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Bulgarian Split Squat", muscle: "Legs", equipment: "Dumbbell", difficulty: "Intermediate", isCustom: false },
  { name: "Lunges", muscle: "Legs", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Arnold Press", muscle: "Shoulders", equipment: "Dumbbell", difficulty: "Intermediate", isCustom: false },
  { name: "Front Raise", muscle: "Shoulders", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Upright Row", muscle: "Shoulders", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Shoulder Press Machine", muscle: "Shoulders", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Reverse Fly", muscle: "Shoulders", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Hammer Curl", muscle: "Arms", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Preacher Curl", muscle: "Arms", equipment: "Barbell", difficulty: "Beginner", isCustom: false },
  { name: "Concentration Curl", muscle: "Arms", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Skull Crusher", muscle: "Arms", equipment: "Barbell", difficulty: "Intermediate", isCustom: false },
  { name: "Dumbbell Kickback", muscle: "Arms", equipment: "Dumbbell", difficulty: "Beginner", isCustom: false },
  { name: "Dips", muscle: "Arms", equipment: "Bodyweight", difficulty: "Intermediate", isCustom: false },
  { name: "Leg Raise", muscle: "Core", equipment: "Bodyweight", difficulty: "Beginner", isCustom: false },
  { name: "Russian Twist", muscle: "Core", equipment: "Bodyweight", difficulty: "Beginner", isCustom: false },
  { name: "Ab Wheel Rollout", muscle: "Core", equipment: "Machine", difficulty: "Intermediate", isCustom: false },
  { name: "Cable Crunch", muscle: "Core", equipment: "Cable", difficulty: "Beginner", isCustom: false },
  { name: "Elliptical", muscle: "Cardio", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Stair Climber", muscle: "Cardio", equipment: "Machine", difficulty: "Beginner", isCustom: false },
  { name: "Burpees", muscle: "Cardio", equipment: "Bodyweight", difficulty: "Intermediate", isCustom: false },
  { name: "Jump Rope", muscle: "Cardio", equipment: "Other", difficulty: "Beginner", isCustom: false },
];
